### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by ryanarmstrong** [un-ts/changesets-gitlab#132]
Are there any plans to support monorepos like Turborepo on the roadmap?

**Comment by JounQin** [comment]
changeset supports monorepo

**Comment by ryanarmstrong** [comment]
I must have something set up incorrectly. I have a Turborepo setup that is using pnpm as the package manager, and when the publish step is run, it complained about there being no version in the package.json. Looking closer I realized that it was referring to the root package.json for the entire monorepo.

To confirm I added a version to the top-level package.json and ran the release pipeline again. This time it moved forward in the release process but attempted to publish the entire monorepo as a single package.

I'm sure I am missing something, I am new to publishing packages, and there is an added wrinkle that I am publishing the a private GitLab repository.

Note that the comment job works perfectly, as does the release part where it finds change sets and creates an MR for the release. The issue is that once that release MR gets merged in and release runs again, this time to publish, I run into the above issues.

My setup (note that I have added a placeholder for the domain name to post here):

.gitlab-ci.yml
```
stages:
  - comment
  - release

before_script:
  - apk --no-cache add curl git
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm install --frozen-lockfile

comment:
  image: node:lts-alpine
  stage: comment
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - packages/**/*
      allow_failure: true
  script: pnpm changesets-gitlab comment

release:
  image: node:lts-alpine
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - .changeset/*
  script: pnpm changesets-gitlab
  variables:
    INPUT_PUBLISH: pnpm publish --no-git-checks
```

.npmrc
```
auto-install-peers = true
@web-guild:registry=https://gitlab-master.example.com/api/v4/projects/85178/-/packages/npm/
registry=https://urm.example.com/artifactory/api/npm/sw-ngc-unified-npm-proxy/
//gitlab-master.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}
```

Output of the release job when attempting to publish:
```
[0KRunning with gitlab-runner 16.0.1 (79704081)[0;m
[0K  on ngc-gitlab-runner-01 kmGZf2Qz, system ID: s_e7e47df4e4f0[0;m
section_start:1697850790:resolve_secrets
[0K[0K[36;1mResolving secrets[0;m[0;m
section_end:1697850790:resolve_secrets
[0Ksection_start:1697850790:prepare_executor
[0K[0K[36;1mPreparing the "docker" executor[0;m[0;m
[0KUsing Docker executor with image node:lts-alpine ...[0;m
[0KPulling docker image node:lts-alpine ...[0;m
[0KUsing docker image sha256:d1517ab6615b781f3b81f339100063d1b2b41f1a32a9efb8563ecd1375311c22 for node:lts-alpine with digest node@sha256:435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d ...[0;m
section_end:1697850793:prepare_executor
[0Ksection_start:1697850793:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-kmgzf2qz-project-85178-concurrent-0 via ngc-gitlab-runner-01...
section_end:1697850793:prepare_script
[0Ksection_start:1697850793:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Reinitialized existing Git repository in /builds/web-guild/web-guild/.git/
[32;1mChecking out a3ccc7c5 as detached HEAD (ref is main)...[0;m
Removing node_modules/
Removing packages/example-package/node_modules/
Removing packages/kaf-generator/node_modules/

[32;1mSkipping Git submodules setup[0;m
section_end:1697850795:get_sources
[0Ksection_start:1697850795:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:d1517ab6615b781f3b81f339100063d1b2b41f1a32a9efb8563ecd1375311c22 for node:lts-alpine with digest node@sha256:435dcad253bb5b7f347ebc69c8cc52de7c912eb7241098b920f2fc2d7843183d ...[0;m
[32;1m$ apk --no-cache add curl git[0;m
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/10) Installing ca-certificates (20230506-r0)
(2/10) Installing brotli-libs (1.0.9-r14)
(3/10) Installing libunistring (1.1-r1)
(4/10) Installing libidn2 (2.3.4-r1)
(5/10) Installing nghttp2-libs (1.57.0-r0)
(6/10) Installing libcurl (8.4.0-r0)
(7/10) Installing curl (8.4.0-r0)
(8/10) Installing libexpat (2.5.0-r1)
(9/10) Installing pcre2 (10.42-r1)
(10/10) Installing git (2.40.1-r0)
Executing busybox-1.36.1-r2.trigger
Executing ca-certificates-20230506-r0.trigger
OK: 21 MiB in 27 packages
[32;1m$ curl -L https://unpkg.com/@pnpm/self-installer | node[0;m
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    49    0    49    0     0    356      0 --:--:-- --:--:-- --:--:--   355

100    60    0    60    0     0    320      0 --:--:-- --:--:-- --:--:--   320

100 1186k    0 1186k    0     0  2917k      0 --:--:-- --:--:-- --:--:-- 2917k
Downloading https://registry.npmjs.org/pnpm/-/pnpm-8.9.2.tgz
[32;1m$ pnpm install --frozen-lockfile[0;m
Scope: all 3 workspace projects
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +619
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 619, reused 619, downloaded 0, added 407
Progress: resolved 619, reused 619, downloaded 0, added 619, done

devDependencies:
+ @changesets/cli 2.26.2
+ @turbo/gen 1.10.7
+ changesets-gitlab 0.10.3
+ eslint 8.44.0
+ prettier 3.0.0
+ turbo 1.10.13

Done in 2.4s
[32;1m$ pnpm changesets-gitlab[0;m

::set-output name=published::false

::set-output name=publishedPackages::[]
setting git user
[command]/usr/bin/git config user.name Ryan Armstrong
[command]/usr/bin/git config user.email "gitlab[bot]@users.noreply.gitlab.com"
setting GitLab credentials
No changesets found, attempting to publish any unpublished packages to npm
No .npmrc file found, creating one
[command]/usr/local/bin/pnpm publish --no-git-checks
npm notice 
npm notice package: web-guild@1.0.0
npm notice === Tarball Contents === 
npm notice 275B   .changeset/config.json                                                                            
npm notice 155B   .eslintrc.js                                                                                      
npm notice 626B   .gitlab-ci.yml                                                                                    
npm notice 203B   .prettierrc.yml                                                                                   
npm notice 679B   .vscode/web-guild.code-workspace                                                                  
npm notice 465B   README.md                                                                                         
npm notice 0B     apps/.gitkeep                                                                                     
npm notice 473B   package.json                                                                                      
npm notice 194B   packages/example-package/CHANGELOG.md                                                             
npm notice 528B   packages/example-package/package.json                                                             
npm notice 2.2kB  packages/example-package/README.md                                                                
npm notice 334B   packages/example-package/rollup.config.js                                                         
npm notice 410B   packages/example-package/src/lunchtime.ts                                                         
npm notice 388B   packages/example-package/src/main.ts                                                              
npm notice 102B   packages/example-package/src/millisecondsUntil.ts                                                 
npm notice 1.4kB  packages/example-package/test/test.ts                                                             
npm notice 5.4kB  packages/example-package/tsconfig.json                                                            
npm notice 216B   packages/kaf-generator/constants.ts                                                               
npm notice 415B   packages/kaf-generator/dist/constants.js                                                          
npm notice 10.2kB packages/kaf-generator/dist/index.js                                                              
npm notice 77B    packages/kaf-generator/dist/types.js                                                              
npm notice 3.2kB  packages/kaf-generator/dist/utils.js                                                              
npm notice 4.3kB  packages/kaf-generator/index.ts                                                                   
npm notice 428B   packages/kaf-generator/package.json                                                               
npm notice 41B    packages/kaf-generator/README.md                                                                  
npm notice 1.8kB  packages/kaf-generator/templates/ngc-infra/.gitlab-ci.yml                                         
npm notice 1.6kB  packages/kaf-generator/templates/ngc-infra/Dockerfile                                             
npm notice 1.1kB  packages/kaf-generator/templates/ngc-infra/helm/charts/Chart.yaml                                 
npm notice 18B    packages/kaf-generator/templates/ngc-infra/helm/charts/release.yaml                               
npm notice 1.7kB  packages/kaf-generator/templates/ngc-infra/helm/charts/templates/deployment.yaml                  
npm notice 580B   packages/kaf-generator/templates/ngc-infra/helm/charts/templates/hpa.yml                          
npm notice 2.0kB  packages/kaf-generator/templates/ngc-infra/helm/charts/templates/ingress.yaml                     
npm notice 320B   packages/kaf-generator/templates/ngc-infra/helm/charts/templates/pdb.yml                          
npm notice 2.1kB  packages/kaf-generator/templates/ngc-infra/helm/charts/templates/rollout.yaml                     
npm notice 338B   packages/kaf-generator/templates/ngc-infra/helm/charts/templates/service-deployment-candidate.yaml
npm notice 273B   packages/kaf-generator/templates/ngc-infra/helm/charts/templates/service.yaml                     
npm notice 320B   packages/kaf-generator/templates/ngc-infra/helm/values/preprod.yaml                               
npm notice 353B   packages/kaf-generator/templates/ngc-infra/helm/values/prod.yaml                                  
npm notice 317B   packages/kaf-generator/templates/ngc-infra/helm/values/staging.yaml                               
npm notice 39B    packages/kaf-generator/templates/web-app/.eslintrc.json                                           
npm notice 528B   packages/kaf-generator/templates/web-app/.prettierrc.yml                                          
npm notice 679B   packages/kaf-generator/templates/web-app/.vscode/web-guild.code-workspace                         
npm notice 2.3kB  packages/kaf-generator/templates/web-app/components/AppShell.tsx                                  
npm notice 1.6kB  packages/kaf-generator/templates/web-app/components/Navbar.tsx                                    
npm notice 916B   packages/kaf-generator/templates/web-app/components/Sidebar.tsx                                   
npm notice 1.9kB  packages/kaf-generator/templates/web-app/components/StoreProvider.tsx                             
npm notice 142B   packages/kaf-generator/templates/web-app/next.config.js                                           
npm notice 1.1kB  packages/kaf-generator/templates/web-app/package.json                                             
npm notice 684B   packages/kaf-generator/templates/web-app/pages/_app.tsx                                           
npm notice 210B   packages/kaf-generator/templates/web-app/pages/_document.tsx                                      
npm notice 452B   packages/kaf-generator/templates/web-app/pages/index.tsx                                          
npm notice 25.2kB packages/kaf-generator/templates/web-app/public/favicon.ico                                       
npm notice 1.8kB  packages/kaf-generator/templates/web-app/README.md                                                
npm notice 57B    packages/kaf-generator/templates/web-app/styles/globals.css                                       
npm notice 638B   packages/kaf-generator/templates/web-app/tsconfig.json                                            
npm notice 240B   packages/kaf-generator/tsconfig.json                                                              
npm notice 38B    packages/kaf-generator/types.ts                                                                   
npm notice 2.7kB  packages/kaf-generator/utils.ts                                                                   
npm notice 40B    pnpm-workspace.yaml                                                                               
npm notice 0B     rfcs/.gitkeep                                                                                     
npm notice 269B   turbo.json                                                                                        
npm notice === Tarball Details === 
npm notice name:          web-guild                               
npm notice version:       1.0.0                                   
npm notice filename:      web-guild-1.0.0.tgz                     
npm notice package size:  25.4 kB                                 
npm notice unpacked size: 87.0 kB                                 
npm notice shasum:        c30f58fd2c3a473eebd64d78a6235ccd62686c16
npm notice integrity:     sha512-YNCDZMGl+HQfA[...]z2O40KEmQTkHw==
npm notice total files:   61                                      
npm notice 
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://urm.example.com/artifactory/api/npm/sw-ngc-unified-npm-proxy/
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-21T01_13_24_189Z-debug-0.log
Error: The process '/usr/local/bin/pnpm' failed with exit code 1
    at ExecState._setResult (/builds/web-guild/web-guild/node_modules/.pnpm/@actions+exec@1.1.1/node_modules/@actions/exec/lib/toolrunner.js:592:25)
    at ExecState.CheckComplete (/builds/web-guild/web-guild/node_modules/.pnpm/@actions+exec@1.1.1/node_modules/@actions/exec/lib/toolrunner.js:575:18)
    at ChildProcess.<anonymous> (/builds/web-guild/web-guild/node_modules/.pnpm/@actions+exec@1.1.1/node_modules/@actions/exec/lib/toolrunner.js:469:27)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
section_end:1697850805:step_script
[0Ksection_start:1697850805:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1697850805:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```

Any guidance would be greatly appreciated!

**Comment by JounQin** [comment]
```log
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in to https://urm.example.com/artifactory/api/npm/sw-ngc-unified-npm-proxy/
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

So you're using a private npm registry right?

https://github.com/un-ts/changesets-gitlab/blob/a8e2cf2957302062a842613a0de72b300e237bbe/src/main.ts#L73-L87

could be related to #78
