### ISSUE TITLE
Job fails with Service Unavailable when releasing multiple packages

### ISSUE THREAD

**Issue by peluprvi** [un-ts/changesets-gitlab#188]
All tags are created, all packages are released and listed in the package registry.
But it fails the job and exits with code 1.

It always fails when releasing 8 or more packages.
Works well with just a few.

I'm in a monorepo using `turbo repo`.

```
GitbeakerRequestError: Service Unavailable
    at throwFailedRequestError (file:///builds/[path_to_project_build]/[project-name]/node_modules/@gitbeaker/rest/dist/index.mjs:41:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async defaultRequestHandler (file:///builds/[path_to_project_build]/[project-name]/node_modules/@gitbeaker/rest/dist/index.mjs:77:7)
    at async file:///builds/[path_to_project_build]/[project-name]/node_modules/@gitbeaker/core/dist/index.mjs:138:22
    at async createRelease (file:///builds/[path_to_project_build]/[project-name]/node_modules/changesets-gitlab/lib/run.js:21:9)
    at async Promise.all (index 6)
    at async runPublish (file:///builds/[path_to_project_build]/[project-name]/node_modules/changesets-gitlab/lib/run.js:79:13)
    at async main (file:///builds/[path_to_project_build]/[project-name]/node_modules/changesets-gitlab/lib/main.js:51:28)
    at async Command.parseAsync (/builds/[path_to_project_build]/[project-name]/node_modules/changesets-gitlab/node_modules/commander/lib/command.js:936:5) {
  cause: {
    description: '{"message":"Upstream Gitaly has been exhausted: maximum queue size reached. Try again later"}',
    request: Request {
      method: 'POST',
      url: 'https://gitlab.com/api/v4/projects/[project_id]/releases',
      headers: Headers {
        'content-type': 'application/json',
        'private-token': '[MASKED]'
      },
      destination: '',
      referrer: 'about:client',
      referrerPolicy: '',
      mode: 'cors',
      credentials: 'same-origin',
      cache: 'default',
      redirect: 'follow',
      integrity: '',
      keepalive: false,
      isReloadNavigation: false,
      isHistoryNavigation: false,
      signal: AbortSignal { aborted: false }
    },
    response: Response {
      status: 503,
      statusText: 'Service Unavailable',
      headers: Headers {
        // removed due to privacy
      },
      body: ReadableStream { locked: true, state: 'closed', supportsBYOB: true },
      bodyUsed: true,
      ok: false,
      redirected: false,
      type: 'basic',
      url: 'https://gitlab.com/api/v4/projects/[project_id]/releases'
    }
  }
}
error Command failed with exit code 1.
```

**Comment by jean-smaug** [comment]
Could also reproduce it when I try to release more than 8 sometime 7 packages

Context is similar PNPM + Turborepo monorepo on Node22

**Comment by minusinus** [comment]
Unfortunately, I don't think the linked PR fixes the issue completely. I just published 27 packages to my projects registry. It fails in the same way. All packages are correctly published into the registry. I am on `1.13.4`.
